#!/bin/bash

# This script must be run prior to commit. The first time it is run, the local repo will be configured to run it
# automatically.

# Configure local repo with .git/pre-commit script.
if [[ ! -e .git/pre-commit ]]; then
  cp _git_pre-commit .git/hooks/pre-commit
  echo "Configured local repo to build SV prior to commit."
fi

# Run this script prior to commit to pre-compile warp-v for CI. This requires a local
# copy of SandPiper (which is why it cannot be done by CI). It cannot be run automatically
# because client-side hooks in git are not part of repo, and the server does not have
# SandPiper.
mkdir -p formal/sp_obj && \
  sandpiper -i formal/warp-v_formal.tlv -o formal/build.sv -p verilog --obj formal/sp_obj && \
  git add formal/build.sv formal/build_gen.sv
