#!/bin/bash

# This script must be run prior to commit. The first time it is run, the local repo will be configured to run it
# automatically.

# Configure local repo with .git/pre-commit script.
if [[ ! -e .git/pre-commit ]]; then
  cp _git_pre-commit .git/pre-commit
  echo "Configured local repo to build SV prior to commit."
fi

# Run this script prior to commit to pre-compile warp-v for CI. This requires a local
# copy of SandPiper (which is why it cannot be done by CI). It cannot be run automatically
# because client-side hooks in git are not part of repo, and the server does not have
# SandPiper.
mkdir -p warpv_formal/sp_obj && \
  sandpiper -i warpv_formal/warp-v_formal_local.tlv -o warpv_formal/build.sv -p verilog --obj warpv_formal/sp_obj && \
  git add warpv_formal/build.sv warpv_formal/build_gen.sv
